/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ypeckstadt;

import org.junit.Test;

public class ArtMainTest {
    @Test public void appHasAGreeting() {
        ArtMain classUnderTest = new ArtMain();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
